### ISSUE TITLE
Terminar formulario de compras

### ISSUE THREAD

**Issue by gabo592** [gabo592/Artemis#6]
# TO-DO

- [ ] Implementar el botón "Ver historial de compras"
- [ ] Implementar el botón "Ver productos"
- [ ] Implementar el botón "Ver proveedores"
- [ ] Cargar el ComboBox de Categorías
- [ ] Implementar el botón de "Añadir producto"
- [ ] Implementar el botón de "Añadir nueva categoría"
- [ ] Implementar el botón de "Añadir al carrito"
- [ ] Implementar el botón de "Eliminar del carrito"
- [ ] Implementar el botón de "Modificar producto"
- [ ] Calcular el subtotal, IVA, y total en base al carrito de compras
- [ ] Implementar el botón de "Limpiar"
- [ ] Implementar el botón de "Comprar"

**Comment by gabo592** [comment]
- [ ] Implementar buscador de compras
